$modelname "D:\Work\HL\towerdefence\sc_towerdefense_2009\playermodel\source\thirdtry\thirdtry.mdl"
$cd "\Work\HL\towerdefence\sc_towerdefense_2009\playermodel\source\thirdtry\"
$cdtexture "\Work\HL\towerdefence\sc_towerdefense_2009\playermodel\source\thirdtry\"
$cliptotextures

$scale 1.0

// 0 attachments

// 0 bone controllers

// 2 hit boxes
$hbox 0 "joint1" -30.000000 -1.000000 0.000000  30.000000 0.000000 60.000000
$hbox 0 "joint1" -30.000000 0.000000 -1.000000  30.000000 60.000000 0.000000

$bodygroup studio
{
studio "thirdtry"
}

// 1 sequences
$sequence idle "idle" fps 30 
