$modelname "D:\Work\HL\towerdefence\sc_towerdefense_2009\playermodel\source\thirdtry\egg\player.mdl"
$cd "\Work\HL\towerdefence\sc_towerdefense_2009\playermodel\source\thirdtry\egg\"
$cdtexture "\Work\HL\towerdefence\sc_towerdefense_2009\playermodel\source\thirdtry\egg\"
$cliptotextures

$scale 1.0

// 0 attachments

// 0 bone controllers

// 1 hit boxes
$hbox 0 "GeoSphere01" -23.910000 -14.910000 -0.150000  34.049999 15.870000 26.850000

$bodygroup studio
{
studio "egg_reference"
}

// 1 sequences
$sequence idle "idle" fps 30 
